Cleaning nav_history.csv

In [6]:
import pandas as pd
import os
import sqlalchemy as sq
import sqlite3
from pathlib import Path
import datetime

In [7]:
data_path="../data/raw"

nav_history=pd.read_csv(os.path.join(data_path,"02_nav_history.csv"))

print(nav_history.head())

print("Shape: ",nav_history.shape)

print("Null Values: ",nav_history.isnull().sum())

print("Data Types: ",nav_history.dtypes)

print("Info: ",nav_history.info())

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692
Shape:  (46000, 3)
Null Values:  amfi_code    0
date         0
nav          0
dtype: int64
Data Types:  amfi_code      int64
date          object
nav          float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB
Info:  None

In [8]:
nav_history["date"]=pd.to_datetime(nav_history["date"])
nav_history.head()

   amfi_code       date      nav
0     119551 2022-01-03  54.3856
1     119551 2022-01-04  54.3474
2     119551 2022-01-05  54.6869
3     119551 2022-01-06  55.4550
4     119551 2022-01-07  55.3692

In [9]:
nav_history.sort_values(by=["amfi_code","date"])

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [10]:
print(nav_history.isnull().sum())

amfi_code    0
date         0
nav          0
dtype: int64

In [11]:
nav_history["nav"]=(nav_history.groupby("amfi_code")["nav"].ffill())

In [12]:
print("Length before Removing Duplicates",len(nav_history))

nav_history=nav_history.drop_duplicates()

print("Length after Removing duplicates: ",len(nav_history))

Length before Removing Duplicates 46000
Length after Removing duplicates:  46000

In [13]:
invalid_nav= nav_history[nav_history["nav"]<=0]
print("Inavlid Nav : ",invalid_nav)

Inavlid Nav :  Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [14]:
nav_history=nav_history[nav_history['nav']>0]

In [15]:
datapath="../data/processed"
nav_history.to_csv(os.path.join(datapath,"clean_nav.csv"),index=False)
print("Cleaned nav history file saved in processed folder")

Cleaned nav history file saved in processed folder

Cleaning investor_transaction.csv

In [16]:
inv_trns=pd.read_csv(os.path.join(data_path,"08_investor_transactions.csv"))
print("Columns: ",inv_trns.columns)

print("Shape: ",inv_trns.shape)

print("Data types: ",inv_trns.dtypes)

print("Missing: ",inv_trns.isnull().sum())

Columns:  Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='object')
Shape:  (32778, 13)
Data types:  investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object
Missing:  investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [17]:
print(inv_trns["transaction_type"].value_counts())

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [18]:
invalid_amount=inv_trns[inv_trns["amount_inr"]<=0]
print("Invalid amounts : ",len(invalid_amount))
inv_trns=inv_trns[inv_trns["amount_inr"]>0]

Invalid amounts :  0

In [19]:
inv_trns["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [20]:
inv_trns["transaction_date"]=pd.to_datetime(inv_trns["transaction_date"])

In [21]:
inv_trns.to_csv(os.path.join(datapath,"clean_transactions.csv"),index=False)
print("Cleaned File stored in Processed folder.")

Cleaned File stored in Processed folder.

Cleaning Scheme Performance file

In [22]:
sch_per=pd.read_csv(os.path.join(data_path,"07_scheme_performance.csv"))
print("Data types: ",sch_per.dtypes)

sch_per.columns = sch_per.columns.str.strip()

print(sch_per.columns.tolist())

Data types:  amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

In [23]:
return_cols=["return_1yr_pct","return_3yr_pct","return_5yr_pct"]
try:
    for col in return_cols:
        sch_per[col]=pd.to_numeric(sch_per[col],errors="coerce")
    print("Changed Return value to numeric")
except Exception as e:
    print(e)

Changed Return value to numeric

In [24]:
negative_sharpe=sch_per[sch_per["sharpe_ratio"]<0]
print("Negative Sharpe Ratios: ",len(negative_sharpe))

Negative Sharpe Ratios:  0

In [25]:
invalid_expn_ratio=sch_per[~sch_per["expense_ratio_pct"].between(0.1,2.5)]
print("Invalid Expence ratio: ",len(invalid_expn_ratio))

Invalid Expence ratio:  0

In [26]:
sch_per.to_csv(os.path.join(datapath,"clean_performance.csv"),index=False)
print("Cleaned File saved in processed folder")

Cleaned File saved in processed folder

Loading Cleaned csv files data into database

In [27]:
from sqlalchemy import create_engine
import sqlalchemy

In [ ]:
dim_nav=pd.read_csv(os.path.join("../data/processed","clean_nav.csv"))
fact_performance=pd.read_csv(os.path.join("../data/processed","clean_performance.csv"))
fact_transaction=pd.read_csv(os.path.join("../data/processed","clean_transactions.csv"))

In [42]:
engine=create_engine(
    "sqlite:///../data/processed/bluestock_mf.db"
)
dim_nav.to_sql(
    "dim_nav",
    engine,
    if_exists="replace",
    index=False
    )
fact_performance.to_sql(
    "fact_performance",
    engine,
    if_exists="replace",
    index=False
)
fact_transaction.to_sql(
    "fact_transaction",
    engine,
    if_exists="replace",
    index=False
)

32778

In [43]:
pd.read_sql("select * from dim_nav limit 4",engine)
pd.read_sql("select * from fact_transaction limit 4",engine)
pd.read_sql("select * from fact_performance limit 4 ",engine)

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High

In [47]:
print("Row counts of CSV files: \ndim_nav: ",len(dim_nav),"\nFact_performance: ",len(fact_performance),"\nFact_transaction: ",len(fact_transaction))
print("Row counts of Database")
pd.read_sql("select count(*) as dim_nav_count from dim_nav",engine)
pd.read_sql("select count(*) as fact_performance_count from fact_performance",engine)
pd.read_sql("select count(*) as fact_transaction_count from fact_transaction",engine)

Row counts of CSV files:
dim_nav:  46000
Fact_performance:  40
Fact_transaction:  32778
Row counts of Database

   fact_transaction_count
0                   32778